# docker-compose.yml

version: '2'
services:
  three-layer:
    image: DOCKER_HUB_IMAGE_TAG
    ports:
      - "3000:3000"
    links:
      - depend_service:depend_service
    user: three-layer
    environment:
      PARA1: XXXXX
      PARA2: YYYYY
    command: three-layer
    volumes:
      - "three-layer_config_path:/var/three-layer/config"
      - "three-layer_data_path:/var/three-layer/data"
    depends_on:
      - depend_service
    restart: unless-stopped
  depend_service:
    build: depend_service
    ports:
      - "5432:5432"
    user: depend_service
    environment:
      DEPEND_SERVICE_PARA1: ZZZZ
    command: depend_service
    volumes:
      - "depend_service_path:/var/lib/depend_service_path"
      - "depend_service_data_path:/depend_service_data"
    restart: unless-stopped
